(function () {
  "use strict";
  const codes = ["en", "zh", "zh_tw", "ja", "ko", "fr"];
  const copy = {
    "Custom Ring Binders & Stationery | LongDe Yizhi": ["Custom Ring Binders & Stationery | LongDe Yizhi", "定制活页夹与文具 | 龙德益智", "客製活頁夾與文具 | 龍德益智", "カスタムリングバインダー・文具 | LongDe Yizhi", "맞춤 링 바인더 및 문구 | LongDe Yizhi", "Classeurs et papeterie sur mesure | LongDe Yizhi"],
    "Develop custom ring binders and stationery products in EVA, PVC, PP and TPU. Configure material, format, hardware and finish for your B2B project.": ["Develop custom ring binders and stationery products in EVA, PVC, PP and TPU. Configure material, format, hardware and finish for your B2B project.", "定制 EVA、PVC、PP 和 TPU 活页夹及文具产品。为您的 B2B 项目选择材料、规格、五金和表面效果。", "客製 EVA、PVC、PP 與 TPU 活頁夾及文具產品。為您的 B2B 專案選擇材料、規格、五金與表面效果。", "EVA、PVC、PP、TPUのカスタムバインダー・文具を開発。B2B案件に合わせて素材、サイズ、金具、仕上げを設定できます。", "EVA, PVC, PP, TPU 맞춤 바인더 및 문구 제품을 개발합니다. B2B 프로젝트에 맞춰 소재, 규격, 하드웨어와 마감을 구성하세요.", "Développez des classeurs et articles de papeterie EVA, PVC, PP et TPU. Configurez matériau, format, quincaillerie et finition pour votre projet B2B."],
    "Products": ["Products", "产品中心", "產品中心", "製品", "제품", "Produits"],
    "Custom Manufacturing": ["Custom Manufacturing", "定制制造", "客製製造", "カスタム製造", "맞춤 제조", "Fabrication sur mesure"],
    "Capability": ["Capability", "制造能力", "製造能力", "製造能力", "제조 역량", "Capacités"],
    "Why LDYZ": ["Why LDYZ", "关于我们", "關於我們", "LDYZについて", "LDYZ 소개", "À propos de LDYZ"],
    "Request a Quote": ["Request a Quote", "获取报价", "索取報價", "見積もりを依頼", "견적 요청", "Demander un devis"],
    "Products / Stationery & Office Products": ["Products / Stationery & Office Products", "产品中心 / 办公及文具用品", "產品中心 / 辦公及文具用品", "製品 / オフィス・文具用品", "제품 / 사무·문구용품", "Produits / Papeterie et fournitures de bureau"],
    "STATIONERY & OFFICE PRODUCTS": ["STATIONERY & OFFICE PRODUCTS", "办公及文具用品", "辦公及文具用品", "オフィス・文具用品", "사무·문구용품", "PAPETERIE ET BUREAU"],
    "Custom ring binders for stationery brands and importers.": ["Custom ring binders for stationery brands and importers.", "为文具品牌和进口商定制活页夹。", "為文具品牌與進口商客製活頁夾。", "文具ブランド・輸入業者向けのカスタムリングバインダー。", "문구 브랜드와 수입업체를 위한 맞춤 링 바인더.", "Classeurs à anneaux personnalisés pour les marques et importateurs de papeterie."],
    "Develop a binder around your market, format and brand. Share a drawing, reference sample or configuration to discuss materials, construction, surface finish and packaging.": ["Develop a binder around your market, format and brand. Share a drawing, reference sample or configuration to discuss materials, construction, surface finish and packaging.", "根据您的市场、规格和品牌开发活页夹。您可发送图纸、参考样品或配置方案，与我们讨论材料、结构、表面处理和包装。", "依據您的市場、規格與品牌開發活頁夾。您可提供圖面、參考樣品或配置方案，與我們討論材料、結構、表面處理與包裝。", "市場・サイズ・ブランドに合わせてバインダーを開発します。図面、参考サンプルまたは仕様案を共有いただき、素材・構造・表面仕上げ・包装をご相談ください。", "시장, 규격, 브랜드에 맞춘 바인더를 개발합니다. 도면, 참고 샘플 또는 사양을 공유해 소재, 구조, 표면 마감 및 포장을 상담하세요.", "Développez un classeur adapté à votre marché, format et marque. Partagez un plan, un échantillon ou une configuration pour discuter des matériaux, de la structure, des finitions et de l’emballage."],
    "PRODUCT CAPABILITIES": ["PRODUCT CAPABILITIES", "产品能力", "產品能力", "製品対応力", "제품 역량", "CAPACITÉS PRODUIT"],
    "Built around your specification": ["Built around your specification", "围绕您的规格开发", "依照您的規格開發", "ご仕様に合わせて開発", "요구 사양에 맞춘 개발", "Conçu selon votre cahier des charges"],
    "Materials": ["Materials", "材料", "材料", "素材", "소재", "Matériaux"],
    "EVA, PVC, PP and TPU options, selected for the intended use and construction.": ["EVA, PVC, PP and TPU options, selected for the intended use and construction.", "可选 EVA、PVC、PP 和 TPU，并根据用途与结构进行评估。", "可選 EVA、PVC、PP 與 TPU，並依用途及結構評估。", "用途と構造に応じてEVA、PVC、PP、TPUから選定します。", "용도와 구조에 따라 EVA, PVC, PP, TPU를 선택할 수 있습니다.", "Options EVA, PVC, PP et TPU sélectionnées selon l’usage et la construction."],
    "Surface & structure": ["Surface & structure", "表面与结构", "表面與結構", "表面・構造", "표면 및 구조", "Surface et structure"],
    "Discuss translucent or frosted covers, printing, EVA lamination or foil stamping, ring systems and closures.": ["Discuss translucent or frosted covers, printing, EVA lamination or foil stamping, ring systems and closures.", "可讨论半透明或磨砂封面、印刷、EVA 贴合或烫箔，以及活页环系统和扣合方式。", "可討論半透明或霧面封面、印刷、EVA 貼合或燙箔，以及活頁環系統與扣合方式。", "半透明・フロスト表紙、印刷、EVAラミネート・箔押し、リング機構や留め具をご相談いただけます。", "반투명 또는 무광 커버, 인쇄, EVA 라미네이팅·박 인쇄, 링 시스템과 잠금 방식을 상담할 수 있습니다.", "Étudiez les couvertures translucides ou givrées, l’impression, le laminage EVA, le marquage à chaud, les anneaux et fermetures."],
    "Project details": ["Project details", "项目需求", "專案需求", "プロジェクト要件", "프로젝트 세부 정보", "Détails du projet"],
    "Share your target format, dimensions, artwork, hardware preference and packaging requirements for review.": ["Share your target format, dimensions, artwork, hardware preference and packaging requirements for review.", "请提供目标规格、尺寸、图稿、五金偏好和包装要求，以便评估。", "請提供目標規格、尺寸、圖稿、五金偏好與包裝需求，以便評估。", "希望サイズ、寸法、デザインデータ、金具の希望、包装要件を共有ください。", "희망 규격, 치수, 아트워크, 하드웨어 선호 및 포장 요구사항을 알려주세요.", "Partagez le format, les dimensions, le visuel, les préférences de quincaillerie et les exigences d’emballage."],
    "FEATURED PRODUCT": ["FEATURED PRODUCT", "重点产品", "重點產品", "注目製品", "주요 제품", "PRODUIT PHARE"],
    "Transparent ring binder collection": ["Transparent ring binder collection", "透明活页夹系列", "透明活頁夾系列", "透明リングバインダーシリーズ", "투명 링 바인더 컬렉션", "Collection de classeurs transparents"],
    "Clear EVA/PVC binder construction with pastel hardware, shaker details and custom colour options.": ["Clear EVA/PVC binder construction with pastel hardware, shaker details and custom colour options.", "透明 EVA/PVC 活页夹结构，可搭配马卡龙色五金、摇摇乐细节及定制颜色。", "透明 EVA/PVC 活頁夾結構，可搭配馬卡龍色五金、搖搖樂細節及客製色彩。", "透明EVA/PVC構造にパステル金具、シェーカー仕様、カスタムカラーを組み合わせられます。", "투명 EVA/PVC 구조에 파스텔 하드웨어, 셰이커 디테일과 맞춤 색상을 적용할 수 있습니다.", "Structure EVA/PVC transparente, quincaillerie pastel, détails shaker et coloris personnalisés."],
    "Product visuals are design examples for discussion and may differ from approved production samples. Final materials, construction and hardware are confirmed against an agreed physical sample.": ["Product visuals are design examples for discussion and may differ from approved production samples. Final materials, construction and hardware are confirmed against an agreed physical sample.", "产品图片为沟通示意，可能与确认后的量产样品不同。最终材料、结构及五金以双方确认的实物样品为准。", "產品圖片為溝通示意，可能與確認後的量產樣品不同。最終材料、結構及五金以雙方確認的實物樣品為準。", "製品画像は打ち合わせ用のイメージで、承認済み量産サンプルと異なる場合があります。最終仕様は合意した実物サンプルで確認します。", "제품 이미지는 상담용 예시이며 승인된 생산 샘플과 다를 수 있습니다. 최종 소재, 구조 및 하드웨어는 합의된 실물 샘플을 기준으로 확정합니다.", "Les visuels sont indicatifs et peuvent différer des échantillons approuvés. Les matériaux, la structure et la quincaillerie définitifs sont validés sur échantillon physique."],
    "Transparent binder": ["Transparent binder", "透明活页夹", "透明活頁夾", "透明バインダー", "투명 바인더", "Classeur transparent"],
    "Colour options": ["Colour options", "颜色选项", "顏色選項", "カラー展開", "색상 옵션", "Options de couleur"],
    "Shaker binder": ["Shaker binder", "摇摇乐活页夹", "搖搖樂活頁夾", "シェーカーバインダー", "셰이커 바인더", "Classeur shaker"],
    "Shaker binder in use": ["Shaker binder in use", "摇摇乐活页夹场景", "搖搖樂活頁夾情境", "シェーカーバインダー使用例", "셰이커 바인더 사용 장면", "Classeur shaker en situation"],
    "BINDER CONFIGURATION STUDIO": ["BINDER CONFIGURATION STUDIO", "活页夹配置工具", "活頁夾配置工具", "バインダー仕様作成ツール", "바인더 구성 도구", "Configurateur de classeur"],
    "Build a binder brief.": ["Build a binder brief.", "搭建您的活页夹需求方案。", "建立您的活頁夾需求方案。", "バインダーの仕様案を作成", "바인더 사양서를 구성하세요.", "Préparez votre brief classeur."],
    "Explore a visual starting point, then send the configuration to our team for engineering review. The preview communicates appearance and proportions; it is not a production drawing.": ["Explore a visual starting point, then send the configuration to our team for engineering review. The preview communicates appearance and proportions; it is not a production drawing.", "先通过可视化预览确定方向，再将配置发送给我们进行工程评估。预览用于展示外观和比例，不是生产图纸。", "先透過視覺預覽確定方向，再將配置傳送給我們進行工程評估。預覽用於呈現外觀與比例，並非生產圖面。", "プレビューで仕様案を検討し、技術確認のため当社へ送信してください。外観と比率の参考であり、製造図面ではありません。", "시각적 미리보기로 방향을 정한 뒤 엔지니어링 검토를 요청하세요. 외관과 비율 참고용이며 생산 도면은 아닙니다.", "Explorez une première configuration, puis envoyez-la à notre équipe pour examen technique. L’aperçu illustre l’apparence et les proportions, pas un plan de production."],
    "LIVE PREVIEW": ["LIVE PREVIEW", "实时预览", "即時預覽", "ライブプレビュー", "실시간 미리보기", "APERÇU EN DIRECT"],
    "Illustrative · factory review required": ["Illustrative · factory review required", "示意预览 · 需工厂确认", "示意預覽 · 需工廠確認", "参考表示・工場確認が必要", "참고용 · 공장 확인 필요", "Illustration · validation usine requise"],
    "Front": ["Front", "正面", "正面", "正面", "정면", "Face"], "Side structure": ["Side structure", "侧面结构", "側面結構", "側面構造", "측면 구조", "Structure latérale"],
    "Finished cover · 170 × 235 mm": ["Finished cover · 170 × 235 mm", "成品封面 · 170 × 235 毫米", "成品封面 · 170 × 235 毫米", "完成表紙 · 170 × 235 mm", "완성 커버 · 170 × 235 mm", "Couverture finie · 170 × 235 mm"],
    "Clear PVC · 0.50 mm · white translucent": ["Clear PVC · 0.50 mm · white translucent", "透明 PVC · 0.50 毫米 · 半透明白", "透明 PVC · 0.50 毫米 · 半透明白", "透明PVC · 0.50 mm · 白半透明", "투명 PVC · 0.50 mm · 반투명 화이트", "PVC transparent · 0,50 mm · blanc translucide"],
    "6 rings · 25 mm inner diameter · 2 snaps": ["6 rings · 25 mm inner diameter · 2 snaps", "6 环 · 内径 25 毫米 · 双扣", "6 環 · 內徑 25 毫米 · 雙扣", "6リング · 内径25 mm · スナップ2個", "6링 · 내경 25 mm · 스냅 2개", "6 anneaux · diamètre intérieur 25 mm · 2 boutons-pression"],
    "Colour and surface are screen simulations. Hole pitch, mechanism fit, snap placement, material and final dimensions require factory confirmation.": ["Colour and surface are screen simulations. Hole pitch, mechanism fit, snap placement, material and final dimensions require factory confirmation.", "颜色和表面效果为屏幕模拟。孔距、夹具适配、扣位、材料和最终尺寸均需工厂确认。", "顏色與表面效果為螢幕模擬。孔距、夾具適配、扣位、材料與最終尺寸均需工廠確認。", "色と表面は画面上のシミュレーションです。穴ピッチ、機構適合、スナップ位置、素材、最終寸法は工場確認が必要です。", "색상과 표면은 화면 시뮬레이션입니다. 홀 간격, 메커니즘 호환, 스냅 위치, 소재와 최종 치수는 공장 확인이 필요합니다.", "Les couleurs et finitions sont simulées à l’écran. Le pas des trous, le mécanisme, les boutons, le matériau et les dimensions finales doivent être confirmés par l’usine."],
    "Edit configuration": ["Edit configuration", "编辑配置", "編輯配置", "仕様を編集", "구성 편집", "Modifier la configuration"],
    "Close configuration options": ["Close configuration options", "收起配置选项", "收合配置選項", "設定を閉じる", "구성 옵션 닫기", "Fermer les options"],
    "1 · Paper & finished size": ["1 · Paper & finished size", "1 · 内页与成品尺寸", "1 · 內頁與成品尺寸", "1 · 用紙・完成サイズ", "1 · 내지 및 완성 크기", "1 · Papier et dimensions finies"],
    "Paper size / system": ["Paper size / system", "内页尺寸 / 装订系统", "內頁尺寸 / 裝訂系統", "用紙サイズ / システム", "용지 크기 / 시스템", "Format papier / système"],
    "Insert width (mm)": ["Insert width (mm)", "内页宽度（毫米）", "內頁寬度（毫米）", "用紙幅（mm）", "내지 너비(mm)", "Largeur de l’insert (mm)"],
    "Insert height (mm)": ["Insert height (mm)", "内页高度（毫米）", "內頁高度（毫米）", "用紙高さ（mm）", "내지 높이(mm)", "Hauteur de l’insert (mm)"],
    "Ring / hole count": ["Ring / hole count", "环数 / 孔数", "環數 / 孔數", "リング / 穴数", "링 / 홀 수", "Nombre d’anneaux / trous"],
    "Finished cover width (mm)": ["Finished cover width (mm)", "成品封面宽度（毫米）", "成品封面寬度（毫米）", "完成カバー幅（mm）", "완성 커버 너비(mm)", "Largeur de couverture finie (mm)"],
    "Finished cover height (mm)": ["Finished cover height (mm)", "成品封面高度（毫米）", "成品封面高度（毫米）", "完成カバー高さ（mm）", "완성 커버 높이(mm)", "Hauteur de couverture finie (mm)"],
    "Closed spine depth (mm)": ["Closed spine depth (mm)", "合拢书脊厚度（毫米）", "合起書脊厚度（毫米）", "閉じた背幅（mm）", "닫힌 등 두께(mm)", "Épaisseur du dos fermé (mm)"],
    "Ring inner diameter (mm)": ["Ring inner diameter (mm)", "活页环内径（毫米）", "活頁環內徑（毫米）", "リング内径（mm）", "링 내경(mm)", "Diamètre intérieur de l’anneau (mm)"],
    "Custom…": ["Custom…", "自定义…", "自訂…", "カスタム…", "사용자 지정…", "Personnalisé…"],
    "Paper dimensions follow common ISO sizes; binder cover and mechanism fit are indicative and require factory confirmation.": ["Paper dimensions follow common ISO sizes; binder cover and mechanism fit are indicative and require factory confirmation.", "内页尺寸参考常见 ISO 规格；封面与夹具适配仅供参考，需工厂确认。", "內頁尺寸參考常見 ISO 規格；封面與夾具適配僅供參考，需工廠確認。", "用紙寸法は一般的なISOサイズを参考にしています。カバーと機構の適合は参考値で、工場確認が必要です。", "용지 치수는 일반적인 ISO 규격을 따릅니다. 커버와 메커니즘 호환은 참고용이며 공장 확인이 필요합니다.", "Les formats papier suivent les tailles ISO courantes ; l’ajustement du mécanisme et de la couverture reste indicatif et doit être confirmé."],
    "2 · Cover material & artwork": ["2 · Cover material & artwork", "2 · 封面材料与图稿", "2 · 封面材料與圖稿", "2 · カバー素材・デザイン", "2 · 커버 소재 및 아트워크", "2 · Matériau de couverture et visuel"],
    "Material": ["Material", "材料", "材料", "素材", "소재", "Matériau"], "Surface": ["Surface", "表面效果", "表面效果", "表面仕上げ", "표면 마감", "Finition"],
    "Clear / translucent": ["Clear / translucent", "透明 / 半透明", "透明 / 半透明", "透明 / 半透明", "투명 / 반투명", "Transparent / translucide"],
    "Frosted": ["Frosted", "磨砂", "霧面", "フロスト", "무광", "Givré"], "Holographic": ["Holographic", "镭射", "雷射", "ホログラム", "홀로그램", "Holographique"], "Printed artwork": ["Printed artwork", "印刷图稿", "印刷圖稿", "印刷デザイン", "인쇄 아트워크", "Visuel imprimé"],
    "Sheet thickness": ["Sheet thickness", "材料厚度", "材料厚度", "シート厚", "시트 두께", "Épaisseur de feuille"],
    "Cover colour · screen preview": ["Cover colour · screen preview", "封面颜色 · 屏幕预览", "封面顏色 · 螢幕預覽", "カバー色 · 画面プレビュー", "커버 색상 · 화면 미리보기", "Couleur de couverture · aperçu écran"],
    "Apply": ["Apply", "应用", "套用", "適用", "적용", "Appliquer"],
    "clear": ["clear", "透明", "透明", "クリア", "투명", "transparent"], "frosted": ["frosted", "磨砂", "霧面", "フロスト", "무광", "givré"], "holographic": ["holographic", "镭射", "雷射", "ホログラム", "홀로그램", "holographique"], "printed": ["printed", "印刷", "印刷", "印刷", "인쇄", "imprimé"],
    "White translucent": ["White translucent", "半透明白", "半透明白", "白半透明", "반투명 화이트", "Blanc translucide"], "Pink": ["Pink", "粉色", "粉紅", "ピンク", "핑크", "Rose"], "Blue": ["Blue", "蓝色", "藍色", "ブルー", "파랑", "Bleu"], "Sage": ["Sage", "鼠尾草绿", "鼠尾草綠", "セージ", "세이지", "Vert sauge"], "Lilac": ["Lilac", "淡紫色", "淡紫色", "ライラック", "라일락", "Lilas"], "Nickel": ["Nickel", "镍色", "鎳色", "ニッケル", "니켈", "Nickel"], "Black": ["Black", "黑色", "黑色", "ブラック", "검정", "Noir"],
    "Add artwork for preview and inquiry": ["Add artwork for preview and inquiry", "上传图稿用于预览和询价", "上傳圖稿用於預覽與詢價", "プレビュー・問い合わせ用のデザインを追加", "미리보기 및 문의용 아트워크 추가", "Ajouter un visuel pour l’aperçu et la demande"],
    "Center": ["Center", "居中", "置中", "中央揃え", "가운데 정렬", "Centrer"], "Remove": ["Remove", "删除", "移除", "削除", "제거", "Supprimer"],
    "Artwork scale": ["Artwork scale", "图稿缩放", "圖稿縮放", "デザイン倍率", "아트워크 배율", "Échelle du visuel"],
    "Drag the artwork on the preview. A local preview URL is created; the file is only sent if you attach it when submitting the inquiry.": ["Drag the artwork on the preview. A local preview URL is created; the file is only sent if you attach it when submitting the inquiry.", "可在预览图上拖动图稿调整位置。图像仅在提交询价时随表单上传。", "可在預覽圖上拖曳圖稿調整位置。圖檔僅會在提交詢價時隨表單上傳。", "プレビュー上でデザインをドラッグして位置を調整できます。画像は問い合わせ送信時にのみアップロードされます。", "미리보기에서 아트워크를 드래그해 위치를 조정할 수 있습니다. 파일은 문의 제출 시에만 업로드됩니다.", "Déplacez le visuel sur l’aperçu. Le fichier sera transmis uniquement avec la demande."],
    "3 · Mechanism & closure": ["3 · Mechanism & closure", "3 · 活页夹与扣合结构", "3 · 活頁夾與扣合結構", "3 · 機構・留め具", "3 · 메커니즘 및 잠금", "3 · Mécanisme et fermeture"],
    "Binder mechanism": ["Binder mechanism", "活页夹型号", "活頁夾型號", "バインダー機構", "바인더 메커니즘", "Mécanisme de classeur"], "Hardware finish": ["Hardware finish", "五金表面处理", "五金表面處理", "金具仕上げ", "하드웨어 마감", "Finition de la quincaillerie"],
    "Mechanism colour": ["Mechanism colour", "活页夹颜色", "活頁夾顏色", "機構カラー", "메커니즘 색상", "Couleur du mécanisme"], "Snap material": ["Snap material", "四合扣材料", "四合扣材質", "スナップ素材", "스냅 소재", "Matériau du bouton-pression"], "Snap count": ["Snap count", "扣子数量", "扣子數量", "スナップ数", "스냅 개수", "Nombre de boutons"],
    "Double snap": ["Double snap", "双扣", "雙扣", "ダブルスナップ", "더블 스냅", "Double bouton-pression"], "Single snap": ["Single snap", "单扣", "單扣", "シングルスナップ", "싱글 스냅", "Simple bouton-pression"],
    "Snap cap diameter (mm)": ["Snap cap diameter (mm)", "扣面直径（毫米）", "扣面直徑（毫米）", "スナップ頭径（mm）", "스냅 캡 직경(mm)", "Diamètre du bouton (mm)"], "Double snap centres (mm)": ["Double snap centres (mm)", "双扣中心距（毫米）", "雙扣中心距（毫米）", "スナップ中心間隔（mm）", "더블 스냅 중심 간격(mm)", "Entraxe des boutons (mm)"], "Closure strap width (mm)": ["Closure strap width (mm)", "扣带宽度（毫米）", "扣帶寬度（毫米）", "ベルト幅（mm）", "잠금 스트랩 너비(mm)", "Largeur de la patte (mm)"], "Strap side": ["Strap side", "扣带位置", "扣帶位置", "ベルト位置", "스트랩 위치", "Position de la patte"], "Right edge": ["Right edge", "右侧", "右側", "右側", "오른쪽", "Côté droit"], "Top edge": ["Top edge", "顶部", "頂部", "上部", "상단", "Haut"],
    "4 · Project details": ["4 · Project details", "4 · 项目信息", "4 · 專案資訊", "4 · プロジェクト情報", "4 · 프로젝트 정보", "4 · Détails du projet"], "Estimated quantity": ["Estimated quantity", "预估数量", "預估數量", "予定数量", "예상 수량", "Quantité estimée"], "Target market": ["Target market", "目标市场", "目標市場", "対象市場", "목표 시장", "Marché cible"], "Reference drawing / image (optional)": ["Reference drawing / image (optional)", "参考图纸 / 图片（选填）", "參考圖面 / 圖片（選填）", "参考図面 / 画像（任意）", "참고 도면 / 이미지(선택)", "Plan / image de référence (facultatif)"],
    "CONFIGURATION BRIEF": ["CONFIGURATION BRIEF", "配置摘要", "配置摘要", "仕様概要", "구성 요약", "RÉCAPITULATIF"], "Quantity and market not entered": ["Quantity and market not entered", "尚未填写数量和市场", "尚未填寫數量與市場", "数量・市場は未入力", "수량 및 시장 미입력", "Quantité et marché non renseignés"], "Save draft": ["Save draft", "保存草稿", "儲存草稿", "下書きを保存", "초안 저장", "Enregistrer le brouillon"], "Download brief": ["Download brief", "下载配置单", "下載配置單", "仕様書をダウンロード", "사양서 다운로드", "Télécharger le brief"], "Send a reference and ask us to recommend": ["Send a reference and ask us to recommend", "发送参考资料并请工厂推荐", "傳送參考資料並請工廠推薦", "参考資料を送って工場に提案を依頼", "참고 자료를 보내고 공장 추천 요청", "Envoyer une référence et demander conseil"],
    "PREPARE YOUR PROJECT INQUIRY": ["PREPARE YOUR PROJECT INQUIRY", "提交项目询价", "提交專案詢價", "プロジェクト問い合わせ", "프로젝트 문의 준비", "PRÉPARER VOTRE DEMANDE"], "Ask our team to review this configuration.": ["Ask our team to review this configuration.", "请我们的团队评估此配置。", "請我們的團隊評估此配置。", "この仕様案の確認を依頼", "이 구성을 검토해 달라고 요청하세요.", "Demandez à notre équipe d’examiner cette configuration."], "Your configuration, preview and selected files will be sent directly to our factory team by email.": ["Your configuration, preview and selected files will be sent directly to our factory team by email.", "您的配置、预览图和所选文件将通过邮件直接发送给工厂团队。", "您的配置、預覽圖與所選檔案將透過電子郵件直接寄送給工廠團隊。", "設定、プレビュー、選択したファイルは工場チームへメールで直接送信されます。", "구성, 미리보기 및 선택한 파일은 이메일로 공장 팀에 직접 전송됩니다.", "Votre configuration, l’aperçu et les fichiers sélectionnés seront envoyés directement à notre équipe par e-mail."],
    "Contact name": ["Contact name", "联系人", "聯絡人", "担当者名", "담당자", "Nom du contact"], "Company": ["Company", "公司", "公司", "会社名", "회사명", "Entreprise"], "Business email": ["Business email", "商务邮箱", "商務電子郵件", "業務用メール", "업무용 이메일", "E-mail professionnel"], "Preferred contact": ["Preferred contact", "首选联系方式", "偏好聯絡方式", "希望する連絡方法", "선호 연락 방법", "Contact préféré"], "Project notes": ["Project notes", "项目说明", "專案說明", "プロジェクトメモ", "프로젝트 메모", "Notes du projet"],
    "I agree that my details and project files may be used to respond to this inquiry.": ["I agree that my details and project files may be used to respond to this inquiry.", "我同意使用我的联系信息和项目文件来回复此询价。", "我同意使用我的聯絡資訊與專案檔案回覆此詢價。", "問い合わせへの回答に、連絡先情報とプロジェクトファイルを使用することに同意します。", "문의 답변을 위해 연락처 정보와 프로젝트 파일을 사용하는 데 동의합니다.", "J’accepte l’utilisation de mes coordonnées et fichiers pour répondre à cette demande."], "Send inquiry with this configuration": ["Send inquiry with this configuration", "发送此配置询价", "傳送此配置詢價", "この仕様で問い合わせる", "이 구성으로 문의 보내기", "Envoyer la demande avec cette configuration"],
    "CUSTOM DEVELOPMENT": ["CUSTOM DEVELOPMENT", "定制开发", "客製開發", "カスタム開発", "맞춤 개발", "DÉVELOPPEMENT SUR MESURE"], "Bring us your product brief.": ["Bring us your product brief.", "告诉我们您的产品需求。", "提供您的產品需求。", "製品のご要望をお聞かせください。", "제품 요구사항을 알려주세요.", "Présentez-nous votre projet."], "Material selection": ["Material selection", "材料选择", "材料選擇", "素材選定", "소재 선택", "Choix des matériaux"], "Printing & finishing": ["Printing & finishing", "印刷与表面处理", "印刷與表面處理", "印刷・仕上げ", "인쇄 및 마감", "Impression et finition"], "Binder construction": ["Binder construction", "活页夹结构", "活頁夾結構", "バインダー構造", "바인더 구조", "Structure du classeur"], "Packaging": ["Packaging", "包装", "包裝", "包装", "포장", "Emballage"], "Discuss your project": ["Discuss your project", "讨论您的项目", "討論您的專案", "プロジェクトを相談", "프로젝트 상담", "Parlons de votre projet"], "SOCIAL RESPONSIBILITY": ["SOCIAL RESPONSIBILITY", "社会责任", "社會責任", "社会的責任", "사회적 책임", "RESPONSABILITÉ SOCIALE"], "BSCI social audit": ["BSCI social audit", "BSCI 社会责任审核", "BSCI 社會責任稽核", "BSCI社会監査", "BSCI 사회 감사", "Audit social BSCI"], "Our factory has undergone an amfori BSCI social audit. Audit documentation is available to qualified buyers on request.": ["Our factory has undergone an amfori BSCI social audit. Audit documentation is available to qualified buyers on request.", "我司工厂已通过 amfori BSCI 社会责任审核。符合条件的采购方可按需索取审核资料。", "本廠已通過 amfori BSCI 社會責任稽核。符合資格的採購方可按需索取稽核資料。", "当社工場はamfori BSCI社会監査を受けています。監査資料は対象となるバイヤーにご要望に応じて提供します。", "당사 공장은 amfori BSCI 사회 감사를 받았습니다. 감사 자료는 자격을 갖춘 구매자에게 요청 시 제공됩니다.", "Notre usine a fait l’objet d’un audit social amfori BSCI. Les documents sont disponibles sur demande pour les acheteurs qualifiés."],
    "Clear PVC": ["Clear PVC", "透明 PVC", "透明 PVC", "透明PVC", "투명 PVC", "PVC transparent"], "Nickel plated metal": ["Nickel plated metal", "镀镍金属", "鍍鎳金屬", "ニッケルメッキ金属", "니켈 도금 금속", "Métal nickelé"], "Painted metal": ["Painted metal", "喷涂金属", "噴塗金屬", "塗装金属", "도장 금속", "Métal peint"], "Plastic": ["Plastic", "塑料", "塑膠", "プラスチック", "플라스틱", "Plastique"], "Stainless steel": ["Stainless steel", "不锈钢", "不鏽鋼", "ステンレス鋼", "스테인리스강", "Acier inoxydable"], "Metal": ["Metal", "金属", "金屬", "金属", "금속", "Métal"],
    "Stationery & Office Products": ["Stationery & Office Products", "办公及文具用品", "辦公及文具用品", "オフィス・文具用品", "사무·문구용품", "Papeterie et fournitures de bureau"],
    "A5 paper · 6 ring (3 + 3)": ["A5 paper · 6 ring (3 + 3)", "A5 内页 · 6 环（3 + 3）", "A5 內頁 · 6 環（3 + 3）", "A5用紙 · 6リング（3 + 3）", "A5 용지 · 6링(3 + 3)", "Papier A5 · 6 anneaux (3 + 3)"],
    "Personal paper · 6 ring (3 + 3)": ["Personal paper · 6 ring (3 + 3)", "Personal 内页 · 6 环（3 + 3）", "Personal 內頁 · 6 環（3 + 3）", "Personal用紙 · 6リング（3 + 3）", "Personal 용지 · 6링(3 + 3)", "Papier Personal · 6 anneaux (3 + 3)"],
    "Pocket paper · 6 ring (3 + 3)": ["Pocket paper · 6 ring (3 + 3)", "Pocket 内页 · 6 环（3 + 3）", "Pocket 內頁 · 6 環（3 + 3）", "Pocket用紙 · 6リング（3 + 3）", "Pocket 용지 · 6링(3 + 3)", "Papier Pocket · 6 anneaux (3 + 3)"],
    "Mini paper · 5 ring": ["Mini paper · 5 ring", "Mini 内页 · 5 环", "Mini 內頁 · 5 環", "Mini用紙 · 5リング", "Mini 용지 · 5링", "Papier Mini · 5 anneaux"],
    "A5 paper · 20 hole": ["A5 paper · 20 hole", "A5 内页 · 20 孔", "A5 內頁 · 20 孔", "A5用紙 · 20穴", "A5 용지 · 20홀", "Papier A5 · 20 trous"],
    "B5 paper · 26 hole": ["B5 paper · 26 hole", "B5 内页 · 26 孔", "B5 內頁 · 26 孔", "B5用紙 · 26穴", "B5 용지 · 26홀", "Papier B5 · 26 trous"],
    "A4 paper · 30 hole": ["A4 paper · 30 hole", "A4 内页 · 30 孔", "A4 內頁 · 30 孔", "A4用紙 · 30穴", "A4 용지 · 30홀", "Papier A4 · 30 trous"],
    "A4 paper · 2 ring": ["A4 paper · 2 ring", "A4 内页 · 2 环", "A4 內頁 · 2 環", "A4用紙 · 2リング", "A4 용지 · 2링", "Papier A4 · 2 anneaux"],
    "A4 paper · 4 ring": ["A4 paper · 4 ring", "A4 内页 · 4 环", "A4 內頁 · 4 環", "A4用紙 · 4リング", "A4 용지 · 4링", "Papier A4 · 4 anneaux"],
    "US Letter · 3 ring": ["US Letter · 3 ring", "美规 Letter · 3 环", "美規 Letter · 3 環", "USレター · 3リング", "US Letter · 3링", "US Letter · 3 anneaux"],
    "Custom size / system": ["Custom size / system", "自定义尺寸 / 系统", "自訂尺寸 / 系統", "カスタムサイズ / システム", "사용자 지정 크기 / 시스템", "Format / système personnalisé"],
    "20 holes": ["20 holes", "20 孔", "20 孔", "20穴", "20홀", "20 trous"], "26 holes": ["26 holes", "26 孔", "26 孔", "26穴", "26홀", "26 trous"], "30 holes": ["30 holes", "30 孔", "30 孔", "30穴", "30홀", "30 trous"],
    "6 rings · 3 + 3": ["6 rings · 3 + 3", "6 环 · 3 + 3", "6 環 · 3 + 3", "6リング · 3 + 3", "6링 · 3 + 3", "6 anneaux · 3 + 3"],
    "5 rings": ["5 rings", "5 环", "5 環", "5リング", "5링", "5 anneaux"], "4 rings": ["4 rings", "4 环", "4 環", "4リング", "4링", "4 anneaux"], "3 rings": ["3 rings", "3 环", "3 環", "3リング", "3링", "3 anneaux"], "2 rings": ["2 rings", "2 环", "2 環", "2リング", "2링", "2 anneaux"],
    "20 holes · fit unconfirmed": ["20 holes · fit unconfirmed", "20 孔 · 适配待确认", "20 孔 · 適配待確認", "20穴 · 適合未確認", "20홀 · 호환 미확인", "20 trous · compatibilité à confirmer"], "26 holes · fit unconfirmed": ["26 holes · fit unconfirmed", "26 孔 · 适配待确认", "26 孔 · 適配待確認", "26穴 · 適合未確認", "26홀 · 호환 미확인", "26 trous · compatibilité à confirmer"], "30 holes · fit unconfirmed": ["30 holes · fit unconfirmed", "30 孔 · 适配待确认", "30 孔 · 適配待確認", "30穴 · 適合未確認", "30홀 · 호환 미확인", "30 trous · compatibilité à confirmer"],
    "6-ring mechanism": ["6-ring mechanism", "6 环夹具", "6 環夾具", "6リング機構", "6링 메커니즘", "Mécanisme 6 anneaux"], "5-ring mechanism": ["5-ring mechanism", "5 环夹具", "5 環夾具", "5リング機構", "5링 메커니즘", "Mécanisme 5 anneaux"], "4-ring mechanism": ["4-ring mechanism", "4 环夹具", "4 環夾具", "4リング機構", "4링 메커니즘", "Mécanisme 4 anneaux"], "3-ring mechanism": ["3-ring mechanism", "3 环夹具", "3 環夾具", "3リング機構", "3링 메커니즘", "Mécanisme 3 anneaux"], "2-ring mechanism": ["2-ring mechanism", "2 环夹具", "2 環夾具", "2リング機構", "2링 메커니즘", "Mécanisme 2 anneaux"],
    "20-hole strip · confirm": ["20-hole strip · confirm", "20 孔条 · 待确认", "20 孔條 · 待確認", "20穴ストリップ · 要確認", "20홀 스트립 · 확인 필요", "Bande 20 trous · à confirmer"], "26-hole strip · confirm": ["26-hole strip · confirm", "26 孔条 · 待确认", "26 孔條 · 待確認", "26穴ストリップ · 要確認", "26홀 스트립 · 확인 필요", "Bande 26 trous · à confirmer"], "30-hole strip · confirm": ["30-hole strip · confirm", "30 孔条 · 待确认", "30 孔條 · 待確認", "30穴ストリップ · 要確認", "30홀 스트립 · 확인 필요", "Bande 30 trous · à confirmer"],
    "e.g. 3,000": ["e.g. 3,000", "例如：3,000", "例如：3,000", "例：3,000", "예: 3,000", "ex. 3 000"], "Country / region": ["Country / region", "国家 / 地区", "國家 / 地區", "国 / 地域", "국가 / 지역", "Pays / région"], "Email / WhatsApp / WeChat": ["Email / WhatsApp / WeChat", "邮箱 / WhatsApp / 微信", "電子郵件 / WhatsApp / 微信", "メール / WhatsApp / WeChat", "이메일 / WhatsApp / WeChat", "E-mail / WhatsApp / WeChat"], "Packaging, target price or any questions": ["Packaging, target price or any questions", "包装、目标价格或其他问题", "包裝、目標價格或其他問題", "包装、目標価格、ご質問など", "포장, 목표 가격 또는 기타 질문", "Emballage, prix cible ou toute question"],
    "Choose cover colour": ["Choose cover colour", "选择封面颜色", "選擇封面顏色", "カバー色を選択", "커버 색상 선택", "Choisir la couleur de couverture"], "Cover HEX colour": ["Cover HEX colour", "封面 HEX 色值", "封面 HEX 色碼", "カバーHEXカラー", "커버 HEX 색상", "Code HEX de la couverture"], "Live binder preview": ["Live binder preview", "活页夹实时预览", "活頁夾即時預覽", "バインダーのライブプレビュー", "바인더 실시간 미리보기", "Aperçu du classeur en direct"], "Preview view": ["Preview view", "预览视图", "預覽視圖", "プレビュー表示", "미리보기 화면", "Vue de l’aperçu"], "Parametric flat illustration of a configured ring binder": ["Parametric flat illustration of a configured ring binder", "按配置参数绘制的活页夹平面示意图", "依配置參數繪製的活頁夾平面示意圖", "設定に応じて描画したバインダー平面図", "구성에 맞춰 그린 바인더 평면도", "Illustration paramétrique à plat du classeur configuré"],
    "Please add artwork for the printed-cover preview, or choose another surface.": ["Please add artwork for the printed-cover preview, or choose another surface.", "请上传封面印刷图稿，或选择其他表面效果。", "請上傳封面印刷圖稿，或選擇其他表面效果。", "印刷カバー用のデザインを追加するか、別の仕上げを選択してください。", "인쇄 커버 미리보기를 위해 아트워크를 추가하거나 다른 마감을 선택하세요.", "Ajoutez un visuel pour l’aperçu imprimé ou choisissez une autre finition."],
    "Attachments must be 15 MB or smaller in total. Remove a file and try again.": ["Attachments must be 15 MB or smaller in total. Remove a file and try again.", "附件总大小需不超过 15 MB，请移除文件后重试。", "附件總大小需不超過 15 MB，請移除檔案後重試。", "添付ファイルは合計15 MB以下にしてください。ファイルを削除して再試行してください。", "첨부 파일은 총 15MB 이하여야 합니다. 파일을 제거하고 다시 시도하세요.", "La taille totale des pièces jointes doit être inférieure à 15 Mo. Supprimez un fichier et réessayez."],
    "Sending your inquiry and attachments…": ["Sending your inquiry and attachments…", "正在发送询价和附件…", "正在傳送詢價與附件…", "問い合わせと添付ファイルを送信中…", "문의 및 첨부 파일 전송 중…", "Envoi de votre demande et des pièces jointes…"],
    "Your inquiry was accepted by the mail server. Our team will reply within one working day.": ["Your inquiry was accepted by the mail server. Our team will reply within one working day.", "邮件服务器已接受您的询价。我们的团队将在一个工作日内回复。", "郵件伺服器已接受您的詢價。我們的團隊將於一個工作日內回覆。", "メールサーバーが問い合わせを受け付けました。1営業日以内に担当者よりご連絡します。", "메일 서버가 문의를 접수했습니다. 영업일 기준 1일 이내에 답변드리겠습니다.", "Votre demande a été acceptée par le serveur de messagerie. Notre équipe vous répondra sous un jour ouvré."],
    "We could not confirm email delivery. Your entries and selected files are still here—please try again later or email sales@longdeyizhi.com directly.": ["We could not confirm email delivery. Your entries and selected files are still here—please try again later or email sales@longdeyizhi.com directly.", "暂未能确认邮件送达。您填写的信息和所选文件仍保留，请稍后重试或直接邮件联系 sales@longdeyizhi.com。", "暫未能確認郵件送達。您填寫的資訊與所選檔案仍保留，請稍後重試或直接寄信至 sales@longdeyizhi.com。", "メールの送信を確認できませんでした。入力内容と選択ファイルは保持されています。後ほど再試行するか、sales@longdeyizhi.comへ直接ご連絡ください。", "이메일 전송을 확인할 수 없습니다. 입력 내용과 선택한 파일은 그대로 유지됩니다. 나중에 다시 시도하거나 sales@longdeyizhi.com으로 직접 이메일을 보내세요.", "La livraison de l’e-mail n’a pas pu être confirmée. Vos saisies et fichiers sont conservés. Réessayez plus tard ou écrivez directement à sales@longdeyizhi.com."],
    "Draft restored. Please re-select any artwork or reference files.": ["Draft restored. Please re-select any artwork or reference files.", "草稿已恢复。请重新选择图稿或参考文件。", "草稿已還原。請重新選擇圖稿或參考檔案。", "下書きを復元しました。デザインや参考ファイルを再選択してください。", "초안을 복원했습니다. 아트워크 또는 참고 파일을 다시 선택하세요.", "Brouillon restauré. Veuillez sélectionner à nouveau les visuels ou fichiers de référence."],
    "Previous draft restored. Please re-select any artwork or reference files.": ["Previous draft restored. Please re-select any artwork or reference files.", "已恢复之前保存的草稿。请重新选择图稿或参考文件。", "已還原先前儲存的草稿。請重新選擇圖稿或參考檔案。", "前回の下書きを復元しました。デザインや参考ファイルを再選択してください。", "이전 초안을 복원했습니다. 아트워크 또는 참고 파일을 다시 선택하세요.", "Le brouillon précédent a été restauré. Sélectionnez à nouveau les visuels ou fichiers de référence."],
    "Paper / system": ["Paper / system", "内页 / 装订系统", "內頁 / 裝訂系統", "用紙 / システム", "용지 / 시스템", "Papier / système"], "Finished size / spine": ["Finished size / spine", "成品尺寸 / 书脊", "成品尺寸 / 書脊", "完成サイズ / 背", "완성 크기 / 등", "Format fini / dos"], "Rings / hardware": ["Rings / hardware", "活页环 / 五金", "活頁環 / 五金", "リング / 金具", "링 / 하드웨어", "Anneaux / quincaillerie"], "Closure": ["Closure", "扣合结构", "扣合結構", "留め具", "잠금 방식", "Fermeture"], "Project": ["Project", "项目", "專案", "プロジェクト", "프로젝트", "Projet"],
    "Transparent six-ring binder main view": ["Transparent six-ring binder main view", "透明六环活页夹主图", "透明六環活頁夾主圖", "透明6リングバインダー正面", "투명 6링 바인더 정면", "Vue principale du classeur transparent à six anneaux"], "Transparent six-ring binder colour options": ["Transparent six-ring binder colour options", "透明六环活页夹颜色选项", "透明六環活頁夾顏色選項", "透明6リングバインダーのカラー", "투명 6링 바인더 색상 옵션", "Options de couleur du classeur transparent à six anneaux"], "Transparent shaker binder main view": ["Transparent shaker binder main view", "透明摇摇乐活页夹主图", "透明搖搖樂活頁夾主圖", "透明シェーカーバインダー正面", "투명 셰이커 바인더 정면", "Vue principale du classeur shaker transparent"], "Transparent shaker binder in a stationery scene": ["Transparent shaker binder in a stationery scene", "文具场景中的透明摇摇乐活页夹", "文具情境中的透明搖搖樂活頁夾", "文具シーンの透明シェーカーバインダー", "문구 장면의 투명 셰이커 바인더", "Classeur shaker transparent dans une scène de papeterie"],
    "Paper": ["Paper", "内页", "內頁", "用紙", "용지", "Papier"], "cover": ["cover", "封面", "封面", "カバー", "커버", "couverture"], "Spine": ["Spine", "书脊", "書脊", "背", "등", "Dos"], "sheet": ["sheet", "材料", "材料", "シート", "시트", "feuille"], "ring ID": ["ring ID", "活页环内径", "活頁環內徑", "リング内径", "링 내경", "diamètre intérieur"], "inner diameter": ["inner diameter", "内径", "內徑", "内径", "내경", "diamètre intérieur"], "ID": ["ID", "内径", "內徑", "内径", "내경", "D.I."], "depth": ["depth", "厚", "厚", "厚", "두께", "épaisseur"], "Cover": ["Cover", "封面", "封面", "カバー", "커버", "Couverture"], "Double": ["Double", "双", "雙", "ダブル", "더블", "Double"], "Single": ["Single", "单", "單", "シングル", "싱글", "Simple"], "snaps": ["snaps", "扣", "扣", "スナップ", "스냅", "boutons"], "snap": ["snap", "扣", "扣", "スナップ", "스냅", "bouton"], "cap": ["cap", "扣面", "扣面", "頭", "캡", "tête"], "centres": ["centres", "中心距", "中心距", "中心間隔", "중심 간격", "entraxe"], "strap": ["strap", "扣带", "扣帶", "ベルト", "스트랩", "patte"],
    "Factory confirmation required: standard paper size does not guarantee mechanism compatibility; confirm cover allowances, ring / hole pitch, snap placement, material and final drawings.": ["Factory confirmation required: standard paper size does not guarantee mechanism compatibility; confirm cover allowances, ring / hole pitch, snap placement, material and final drawings.", "需工厂确认：标准内页尺寸不代表夹具一定适配；封面余量、环距/孔距、扣位、材料和最终图纸均需确认。", "需工廠確認：標準內頁尺寸不代表夾具一定適配；封面餘量、環距/孔距、扣位、材料與最終圖面均需確認。", "工場確認が必要です。標準用紙サイズでも機構適合を保証しません。カバー余白、リング・穴ピッチ、スナップ位置、素材、最終図面を確認してください。", "공장 확인 필요: 표준 용지 크기가 메커니즘 호환성을 보장하지 않습니다. 커버 여유, 링/홀 간격, 스냅 위치, 소재와 최종 도면을 확인하세요.", "Validation usine requise : le format papier standard ne garantit pas la compatibilité. Confirmez les marges, entraxes, positions des boutons, matériaux et plans finaux."],
    "Paper format dimensions are references only. Confirm binder construction and mechanism fit with the factory before sampling.": ["Paper format dimensions are references only. Confirm binder construction and mechanism fit with the factory before sampling.", "纸张规格仅供参考，打样前请与工厂确认活页夹结构和夹具适配。", "紙張規格僅供參考，打樣前請與工廠確認活頁夾結構與夾具適配。", "用紙寸法は参考値です。試作前に構造と機構の適合を工場へご確認ください。", "용지 규격은 참고용입니다. 샘플 제작 전 바인더 구조와 메커니즘 호환을 공장에 확인하세요.", "Les dimensions papier sont indicatives. Confirmez la construction et le mécanisme avec l’usine avant échantillonnage."],
    "This visual is not a production drawing.": ["This visual is not a production drawing.", "此预览不是生产图纸。", "此預覽不是生產圖面。", "この画像は製造図面ではありません。", "이 시각 자료는 생산 도면이 아닙니다.", "Ce visuel n’est pas un plan de production."],
    "Visual proportions only; approve final supplier drawing and physical sample before production.": ["Visual proportions only; approve final supplier drawing and physical sample before production.", "仅展示视觉比例；量产前须确认供应商最终图纸和实物样品。", "僅呈現視覺比例；量產前須確認供應商最終圖面與實物樣品。", "比率の参考表示です。量産前に最終図面と実物サンプルをご承認ください。", "비율 참고용입니다. 생산 전에 최종 공급업체 도면과 실물 샘플을 승인하세요.", "Proportions indicatives ; approuvez le plan final et l’échantillon avant production."],
    "Illustrative · not production artwork": ["Illustrative · not production artwork", "示意预览 · 非生产文件", "示意預覽 · 非生產文件", "参考表示 · 製造用ではありません", "참고용 · 생산용 아님", "Illustration · non destinée à la production"],
    "Quantity not entered": ["Quantity not entered", "未填写数量", "未填數量", "数量未入力", "수량 미입력", "Quantité non renseignée"], "Market not entered": ["Market not entered", "未填写市场", "未填市場", "市場未入力", "시장 미입력", "Marché non renseigné"],
    "Finished width": ["Finished width", "成品宽", "成品寬", "完成幅", "완성 너비", "Largeur finie"], "Front": ["Front", "正面", "正面", "正面", "정면", "Face"], "Side structure · sheet thickness exaggerated to remain visible": ["Side structure · sheet thickness exaggerated to remain visible", "侧面结构 · 为便于观察已放大材料厚度", "側面結構 · 為便於觀察已放大材料厚度", "側面構造 · 見やすさのため厚みを誇張表示", "측면 구조 · 잘 보이도록 시트 두께를 과장 표시", "Structure latérale · épaisseur exagérée pour rester visible"], "Closed spine depth": ["Closed spine depth", "合拢书脊厚度", "合起書脊厚度", "閉じた背幅", "닫힌 등 두께", "Épaisseur du dos fermé"], "Cover material": ["Cover material", "封面材料", "封面材料", "カバー素材", "커버 소재", "Matériau de couverture"], "Ring inner diameter": ["Ring inner diameter", "活页环内径", "活頁環內徑", "リング内径", "링 내경", "Diamètre intérieur de l’anneau"],
    "Draft saved in this browser. Browsers do not retain file selections; keep artwork files separately.": ["Draft saved in this browser. Browsers do not retain file selections; keep artwork files separately.", "草稿已保存在此浏览器中。浏览器不会保留文件选择，请另外保存图稿文件。", "草稿已儲存在此瀏覽器中。瀏覽器不會保留檔案選擇，請另外保存圖稿。", "下書きをこのブラウザーに保存しました。ファイル選択は保存されないため、デザインデータは別途保管してください。", "초안이 이 브라우저에 저장되었습니다. 파일 선택은 저장되지 않으므로 아트워크 파일은 별도로 보관하세요.", "Brouillon enregistré dans ce navigateur. Les fichiers sélectionnés ne sont pas conservés ; gardez vos visuels séparément."],
    "Could not save in this browser. Use Download brief to keep a copy.": ["Could not save in this browser. Use Download brief to keep a copy.", "无法在此浏览器保存，请使用“下载配置单”保留副本。", "無法在此瀏覽器儲存，請使用「下載配置單」保留副本。", "このブラウザーに保存できません。「仕様書をダウンロード」をご利用ください。", "이 브라우저에 저장할 수 없습니다. 사양서 다운로드를 이용해 사본을 보관하세요.", "Impossible d’enregistrer dans ce navigateur. Téléchargez le brief pour en garder une copie."],
    "For the live preview choose a PNG, JPG or WebP image.": ["For the live preview choose a PNG, JPG or WebP image.", "实时预览仅支持 PNG、JPG 或 WebP 图片。", "即時預覽僅支援 PNG、JPG 或 WebP 圖片。", "プレビュー画像にはPNG、JPG、WebPを選択してください。", "미리보기는 PNG, JPG 또는 WebP 이미지 형식을 지원합니다.", "Pour l’aperçu, choisissez une image PNG, JPG ou WebP."],
    "Reference drawings and artwork are attached to your inquiry email. Maximum total attachment size: 15 MB.": ["Reference drawings and artwork are attached to your inquiry email. Maximum total attachment size: 15 MB.", "参考图纸和图稿将作为询价邮件附件发送。附件总大小上限：15 MB。", "參考圖面與圖稿將作為詢價郵件附件寄送。附件總大小上限：15 MB。", "参考図面とデザインは問い合わせメールに添付されます。添付上限：合計15 MB。", "참고 도면과 아트워크는 문의 이메일에 첨부됩니다. 첨부 총 용량 한도: 15MB.", "Les plans et visuels seront joints à votre demande. Taille totale maximale : 15 Mo."],
    "attached to inquiry": ["attached to inquiry", "将随询价发送", "將隨詢價寄送", "問い合わせに添付", "문의에 첨부", "joint à la demande"],
    "Add a reference file in the configuration options above, then complete your contact details. The file and current brief will be included in the inquiry.": ["Add a reference file in the configuration options above, then complete your contact details. The file and current brief will be included in the inquiry.", "请在上方配置中添加参考文件并填写联系方式，文件和当前配置将随询价一并发送。", "請在上方配置中加入參考檔案並填寫聯絡方式，檔案與目前配置將隨詢價一併寄送。", "上の設定で参考ファイルを追加し、連絡先を入力してください。ファイルと現在の仕様を問い合わせに含めます。", "위 구성 옵션에서 참고 파일을 추가하고 연락처를 입력하세요. 파일과 현재 사양을 문의에 포함합니다.", "Ajoutez un fichier de référence ci-dessus et renseignez vos coordonnées ; le fichier et le brief seront inclus dans votre demande."],
    "BINDER CONFIGURATION BRIEF": ["BINDER CONFIGURATION BRIEF", "活页夹配置单", "活頁夾配置單", "バインダー仕様書", "바인더 구성 사양서", "FICHE DE CONFIGURATION DU CLASSEUR"],
    "Prepared for factory review": ["Prepared for factory review", "供工厂评估", "供工廠評估", "工場確認用", "공장 검토용", "Préparé pour examen par l’usine"],
    "PRODUCT SPECIFICATIONS": ["PRODUCT SPECIFICATIONS", "产品规格", "產品規格", "製品仕様", "제품 사양", "SPÉCIFICATIONS DU PRODUIT"],
    "Product": ["Product", "产品", "產品", "製品", "제품", "Produit"], "Product code": ["Product code", "产品编号", "產品編號", "製品コード", "제품 코드", "Code produit"],
    "Paper format": ["Paper format", "内页规格", "內頁規格", "用紙サイズ", "용지 형식", "Format papier"], "Insert size": ["Insert size", "内页尺寸", "內頁尺寸", "リフィル寸法", "내지 크기", "Format des recharges"], "Paper / ring-hole system": ["Paper / ring-hole system", "内页 / 活页环或孔位系统", "內頁 / 活頁環或孔位系統", "用紙 / リング・穴システム", "용지 / 링·홀 시스템", "Papier / système d’anneaux ou de perforation"],
    "Finished cover size": ["Finished cover size", "成品封面尺寸", "成品封面尺寸", "完成カバー寸法", "완성 커버 크기", "Dimensions finies de la couverture"], "Mechanism": ["Mechanism", "夹具", "夾具", "金具", "메커니즘", "Mécanisme"], "Mechanism colour": ["Mechanism colour", "夹具颜色", "夾具顏色", "金具の色", "메커니즘 색상", "Couleur du mécanisme"],
    "Surface finish": ["Surface finish", "表面效果", "表面效果", "表面仕上げ", "표면 마감", "Finition de surface"], "Material thickness": ["Material thickness", "材料厚度", "材料厚度", "素材厚", "소재 두께", "Épaisseur du matériau"], "Cover colour": ["Cover colour", "封面颜色", "封面顏色", "カバー色", "커버 색상", "Couleur de la couverture"], "Artwork": ["Artwork", "印刷图稿", "印刷圖稿", "印刷データ", "인쇄 아트워크", "Visuel"], "Not provided": ["Not provided", "未提供", "未提供", "未提供", "제공되지 않음", "Non fourni"],
    "Snap material": ["Snap material", "四合扣材料", "四合扣材料", "スナップ素材", "스냅 소재", "Matériau du bouton-pression"], "Snap count": ["Snap count", "四合扣数量", "四合扣數量", "スナップ数", "스냅 개수", "Nombre de boutons-pression"], "Snap cap diameter": ["Snap cap diameter", "扣面直径", "扣面直徑", "スナップ頭径", "스냅 캡 지름", "Diamètre de la tête du bouton"], "Double snap centre spacing": ["Double snap centre spacing", "双扣中心距", "雙扣中心距", "2個留め具の中心間隔", "더블 스냅 중심 간격", "Entraxe des deux boutons"], "Strap width": ["Strap width", "扣带宽度", "扣帶寬度", "ベルト幅", "스트랩 너비", "Largeur de la patte"], "Strap side": ["Strap side", "扣带位置", "扣帶位置", "ベルト位置", "스트랩 위치", "Position de la patte"], "Snap colour": ["Snap colour", "四合扣颜色", "四合扣顏色", "スナップの色", "스냅 색상", "Couleur des boutons-pression"],
    "Estimated quantity": ["Estimated quantity", "预计数量", "預計數量", "予定数量", "예상 수량", "Quantité estimée"], "Target market": ["Target market", "目标市场", "目標市場", "対象市場", "목표 시장", "Marché cible"], "Contact": ["Contact", "联系方式", "聯絡方式", "連絡先", "연락처", "Contact"], "Contact name": ["Contact name", "联系人", "聯絡人", "担当者名", "담당자 이름", "Nom du contact"], "Company": ["Company", "公司", "公司", "会社名", "회사", "Entreprise"], "Business email": ["Business email", "商务邮箱", "商務電子郵件", "業務用メール", "업무용 이메일", "E-mail professionnel"], "Preferred contact": ["Preferred contact", "首选联系方式", "首選聯絡方式", "希望する連絡方法", "선호 연락 방법", "Contact préféré"],
    "Important note": ["Important note", "重要说明", "重要說明", "重要事項", "중요 안내", "Note importante"], "Factory confirmation": ["Factory confirmation", "工厂确认", "工廠確認", "工場確認", "공장 확인", "Confirmation par l’usine"], "Configuration brief": ["Configuration brief", "配置单", "配置單", "仕様書", "구성 사양서", "Fiche de configuration"],
    "Custom ring binder": ["Custom ring binder", "定制活页夹", "客製活頁夾", "カスタムバインダー", "맞춤 바인더", "Classeur personnalisé"], "rings": ["rings", "环", "環", "リング", "링", "anneaux"], "holes": ["holes", "孔", "孔", "穴", "홀", "perforations"],
    "A5": ["A5", "A5", "A5", "A5", "A5", "A5"], "A4": ["A4", "A4", "A4", "A4", "A4", "A4"], "Personal": ["Personal", "随身", "隨身", "パーソナル", "퍼스널", "Personal"], "Pocket": ["Pocket", "口袋", "口袋", "ポケット", "포켓", "Poche"], "Mini": ["Mini", "迷你", "迷你", "ミニ", "미니", "Mini"], "JIS B5": ["JIS B5", "JIS B5", "JIS B5", "JIS B5", "JIS B5", "JIS B5"], "US Letter": ["US Letter", "美式信纸", "美式信紙", "レター", "레터", "Format Lettre US"], "Custom": ["Custom", "自定义", "自訂", "カスタム", "사용자 지정", "Personnalisé"],
    "Nickel plated steel": ["Nickel plated steel", "镀镍钢", "鍍鎳鋼", "ニッケルメッキ鋼", "니켈 도금 강철", "Acier nickelé"], "right": ["right", "右侧", "右側", "右側", "오른쪽", "droite"], "top": ["top", "上方", "上方", "上部", "위쪽", "haut"],
    "Illustrative browser preview only. Confirm material, colour, dimensions, hole pitch and hardware fit with factory drawings and an approved sample. Not a production drawing.": ["Illustrative browser preview only. Confirm material, colour, dimensions, hole pitch and hardware fit with factory drawings and an approved sample. Not a production drawing.", "仅为浏览器示意预览。材料、颜色、尺寸、孔距及五金适配均须依据工厂图纸和确认样品核实；本文件不是生产图纸。", "僅為瀏覽器示意預覽。材料、顏色、尺寸、孔距及五金適配均須依據工廠圖面與確認樣品核實；本文件不是生產圖面。", "ブラウザー上の参考プレビューです。素材、色、寸法、穴ピッチ、金具の適合性は工場図面と承認済みサンプルで確認してください。製造図面ではありません。", "브라우저 참고 미리보기입니다. 소재, 색상, 치수, 홀 간격 및 하드웨어 적합성은 공장 도면과 승인 샘플로 확인해야 합니다. 생산 도면이 아닙니다.", "Aperçu indicatif dans le navigateur. Confirmez les matériaux, couleurs, dimensions, entraxes et la compatibilité avec les plans de l’usine et un échantillon approuvé. Ce document n’est pas un plan de production."]
  };
  const originals = new WeakMap();
  const attributeOriginals = new WeakMap();
  let current = "en";
  function translated(text, lang) { const row = copy[text]; return row ? row[codes.indexOf(lang)] || text : text; }
  function capture() {
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) { const node = walker.currentNode; if (!originals.has(node)) originals.set(node, node.nodeValue); }
    document.querySelectorAll("[placeholder],[aria-label],[title]").forEach((el) => {
      if (!attributeOriginals.has(el)) attributeOriginals.set(el, { placeholder: el.getAttribute("placeholder"), aria: el.getAttribute("aria-label"), title: el.getAttribute("title") });
    });
  }
  function setLanguage(lang, persist) {
    if (!codes.includes(lang)) lang = "en";
    current = lang; capture();
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) {
      const node = walker.currentNode, original = originals.get(node);
      if (original == null) continue;
      const trimmed = original.trim();
      if (!trimmed) continue;
      const value = translated(trimmed, lang);
      node.nodeValue = original.replace(trimmed, value);
    }
    document.querySelectorAll("[placeholder],[aria-label],[title]").forEach((el) => {
      const original = attributeOriginals.get(el); if (!original) return;
      [["placeholder", "placeholder"], ["aria-label", "aria"], ["title", "title"]].forEach(([attr, key]) => {
        if (original[key] != null) el.setAttribute(attr, translated(original[key], lang));
      });
    });
    document.documentElement.lang = ({ en: "en", zh: "zh-CN", zh_tw: "zh-TW", ja: "ja", ko: "ko", fr: "fr" })[lang];
    document.title = translated("Custom Ring Binders & Stationery | LongDe Yizhi", lang);
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.content = translated("Develop custom ring binders and stationery products in EVA, PVC, PP and TPU. Configure material, format, hardware and finish for your B2B project.", lang);
    document.querySelectorAll(".stationery-lang-switch [data-lang]").forEach((b) => {
      const active = b.dataset.lang === lang; b.classList.toggle("active", active); b.setAttribute("aria-pressed", String(active));
    });
    const url = new URL(window.location.href); url.searchParams.set("lang", lang);
    try { window.history.replaceState({}, "", url.pathname + url.search + url.hash); } catch (_) {}
    if (persist) { try { localStorage.setItem("longde_site_lang", lang); } catch (_) {} }
    window.dispatchEvent(new CustomEvent("stationery:language", { detail: { lang, t: (text) => translated(text, lang) } }));
  }
  window.stationeryT = (text) => translated(text, current);
  window.getStationeryLanguage = () => current;
  document.addEventListener("click", (event) => {
    const button = event.target.closest(".stationery-lang-switch [data-lang]");
    if (button) setLanguage(button.dataset.lang, true);
  });
  let initial = new URLSearchParams(window.location.search).get("lang");
  if (!codes.includes(initial)) { try { initial = localStorage.getItem("longde_site_lang"); } catch (_) {} }
  if (!codes.includes(initial)) initial = "en";
  document.addEventListener("DOMContentLoaded", () => setLanguage(initial, false));
  if (document.readyState !== "loading") setLanguage(initial, false);
}());
